set_device GW2AR-LV18QN88C8/I7

add_file jtopl/jt2413.v                                                         
add_file jtopl/jtopl.v                                                          
add_file jtopl/jtopl2.v                                                         
add_file jtopl/jtopl_acc.v                                                      
add_file jtopl/jtopl_csr.v                                                      
add_file jtopl/jtopl_div.v                                                      
add_file jtopl/jtopl_eg.v                                                       
add_file jtopl/jtopl_eg_cnt.v                                                   
add_file jtopl/jtopl_eg_comb.v                                                  
add_file jtopl/jtopl_eg_ctrl.v                                                  
add_file jtopl/jtopl_eg_final.v                                                 
add_file jtopl/jtopl_eg_pure.v                                                  
add_file jtopl/jtopl_eg_step.v                                                  
add_file jtopl/jtopl_exprom.v                                                   
add_file jtopl/jtopl_lfo.v                                                      
add_file jtopl/jtopl_logsin.v                                                   
add_file jtopl/jtopl_mmr.v                                                      
add_file jtopl/jtopl_noise.v                                                    
add_file jtopl/jtopl_op.v                                                       
add_file jtopl/jtopl_pg.v                                                       
add_file jtopl/jtopl_pg_comb.v                                                  
add_file jtopl/jtopl_pg_inc.v                                                   
add_file jtopl/jtopl_pg_rhy.v                                                   
add_file jtopl/jtopl_pg_sum.v                                                   
add_file jtopl/jtopl_pm.v                                                       
add_file jtopl/jtopl_reg.v                                                      
add_file jtopl/jtopl_reg_ch.v                                                   
add_file jtopl/jtopl_sh.v                                                       
add_file jtopl/jtopl_sh_rst.v                                                   
add_file jtopl/jtopl_single_acc.v                                               
add_file jtopl/jtopl_slot_cnt.v                                                 
add_file jtopl/jtopl_timers.v                                                   
add_file jtopl/jtopll_mmr.v                                                     
add_file jtopl/jtopll_reg.v                                                     
add_file jtopl/jtopll_reg_ch.v                                                  
add_file src/bios_msx2p.v                                                       
add_file src/gowin/clk_108p.v                                                   
add_file src/impulse.v                                                          
add_file src/logo.v                                                             
add_file src/logo_fm.v                                                          
add_file src/megaram.v                                                          
add_file src/memory.v                                                           
add_file src/pinfilter.v                                                        
add_file src/rtc.v                                                              
add_file src/subrom_msx2p.v                                                     
add_file tn_vdp_v3_v9958/src/clockdiv.v                                         
add_file tn_vdp_v3_v9958/src/gowin/clk_135.v                                    
add_file tn_vdp_v3_v9958/src/hdmi/audio_clock_regeneration_packet.sv            
add_file tn_vdp_v3_v9958/src/hdmi/audio_info_frame.sv                           
add_file tn_vdp_v3_v9958/src/hdmi/audio_sample_packet.sv                        
add_file tn_vdp_v3_v9958/src/hdmi/auxiliary_video_information_info_frame.sv     
add_file tn_vdp_v3_v9958/src/hdmi/hdmi.sv                                       
add_file tn_vdp_v3_v9958/src/hdmi/packet_assembler.sv                           
add_file tn_vdp_v3_v9958/src/hdmi/packet_picker.sv                              
add_file tn_vdp_v3_v9958/src/hdmi/serializer.sv                                 
add_file tn_vdp_v3_v9958/src/hdmi/source_product_description_info_frame.sv      
add_file tn_vdp_v3_v9958/src/hdmi/tmds_channel.sv                               
add_file tn_vdp_v3_v9958/src/memory_controller.v                                
add_file tn_vdp_v3_v9958/src/sdram.v                                            
add_file tn_vdp_v3_v9958/src/v9958_top.v                                        
add_file top.v                                                                  
add_file OCM_3.9/sound/scc/megaram.vhd                                          
add_file OCM_3.9/sound/scc/scc_wave.vhd                                         
add_file PSG_YM2149/YM2149.vhdl                                                 
add_file T80A/t80.vhd                                                           
add_file T80A/t80_alu.vhd                                                       
add_file T80A/t80_mcode.vhd                                                     
add_file T80A/t80_pack.vhd                                                      
add_file T80A/t80_reg.vhd                                                       
add_file T80A/t80a.vhd                                                          
add_file src/gowin_clkdiv2/gowin_clkdiv2.vhd                                    
add_file tn_vdp_v3_v9958/src/ram.vhd                                            
add_file tn_vdp_v3_v9958/src/vdp/vdp.vhd                                        
add_file tn_vdp_v3_v9958/src/vdp/vdp_colordec.vhd                               
add_file tn_vdp_v3_v9958/src/vdp/vdp_command.vhd                                
add_file tn_vdp_v3_v9958/src/vdp/vdp_doublebuf.vhd                              
add_file tn_vdp_v3_v9958/src/vdp/vdp_graphic123m.vhd                            
add_file tn_vdp_v3_v9958/src/vdp/vdp_graphic4567.vhd                            
add_file tn_vdp_v3_v9958/src/vdp/vdp_hvcounter.vhd                              
add_file tn_vdp_v3_v9958/src/vdp/vdp_interrupt.vhd                              
add_file tn_vdp_v3_v9958/src/vdp/vdp_linebuf.vhd                                
add_file tn_vdp_v3_v9958/src/vdp/vdp_ntsc_pal.vhd                               
add_file tn_vdp_v3_v9958/src/vdp/vdp_package.vhd                                
add_file tn_vdp_v3_v9958/src/vdp/vdp_register.vhd                               
add_file tn_vdp_v3_v9958/src/vdp/vdp_spinforam.vhd                              
add_file tn_vdp_v3_v9958/src/vdp/vdp_sprite.vhd                                 
add_file tn_vdp_v3_v9958/src/vdp/vdp_ssg.vhd                                    
add_file tn_vdp_v3_v9958/src/vdp/vdp_text12.vhd                                 
add_file tn_vdp_v3_v9958/src/vdp/vdp_vga.vhd                                    
add_file tn_vdp_v3_v9958/src/vdp/vdp_wait_control.vhd                           
add_file tn_vdp_v3_v9958/src/vdp/vencode.vhd                                    
add_file tang9k.cst                                                             
add_file Z80_goauld.sdc                                                         
# add_file src/Z80_goauld.rao                                                     

set_option -use_sspi_as_gpio 1 -top_module top -verilog_std sysv2017 -include_path src
run syn
run pnr